version: 2.1  # This is the lowest version that supports Orbs

orbs:
  node: circleci/node@1.0.1  # Use node elements in existing workflows and jobs

jobs:
  lint:
    docker:
    - image: node:8.12.0-alpine
    steps:
    - checkout
    - run: npm install
    - run: npm run lint
  
  unit:
    docker:
    - image: node:8.12.0-alpine
    steps:
    - checkout
    - run: npm install
    - run: npm run unit

workflows:
  version: 2

  test:
    jobs:
    - lint
    - unit